apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsportal
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  team: permittering-og-nedbemanning
  port: 3000
  ingresses:
    - https://permitteringsportal.dev.nav.no/permitteringsportal
  liveness:
    path: /permitteringsportal/internal/isAlive
    initialDelay: 5
  readiness:
    path: /permitteringsportal/internal/isReady
    initialDelay: 5
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  idporten:
    sidecar:
      enabled: true
    enabled: true
    clientUri: https://permitteringsportal.dev.nav.no/permitteringsportal
    postLogoutRedirectURIs:
      - https://permitteringsportal.dev.nav.no/permitteringsportal/logout-callback
  accessPolicy:
    outbound:
      rules:
        - application: permitteringsportal-api
      external:
        - host: dekoratoren.dev.nav.no
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_AUDIENCE
      value: dev-gcp:permittering-og-nedbemanning:permitteringsportal-api
    - name: BACKEND_BASEURL
      value: http://permitteringsportal-api
    - name: LOGINSERVICE_LOGOUT_URL
      value: https://loginservice.dev.nav.no/slo
